name: "Build Game"

on:
  workflow_run:
    workflows: ["Quality checks"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:

jobs:
  export_game:
    name: Export Game
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: 0

      - name: Setup directories
        run: mkdir -p ~/.local/share/godot/export_templates ~/.config/godot/ build/web
          
      - name: Install dependencies
        run: apt-get update && apt-get install -y rsync wget unzip

      - name: Cache Godot export templates
        id: cache-templates
        uses: actions/cache@v3
        with:
          path: ~/.local/share/godot/export_templates
          key: ${{ runner.os }}-godot-templates-4.3-stable

      - name: Download and install export templates
        if: steps.cache-templates.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_export_templates.tpz -O templates.tpz
          unzip -q templates.tpz
          mkdir -p ~/.local/share/godot/export_templates/4.3.stable
          mv templates/* ~/.local/share/godot/export_templates/4.3.stable/
          rm -rf templates templates.tpz

      - name: Web Build
        id: web_build
        run: |
          echo "Building web export..."
          godot --headless --export-release "Web" ./build/web/index.html || {
            echo "::set-output name=build_failed::true"
            exit 1
          }
          echo "Web build completed successfully"

      - name: Desktop Build (Optional)
        if: false  # Désactivé par défaut, activez si nécessaire
        run: |
          mkdir -p build/linux
          godot --headless --export-release "Linux/X11" ./build/linux/game.x86_64
          chmod +x ./build/linux/game.x86_64
          
          mkdir -p build/windows
          godot --headless --export-release "Windows Desktop" ./build/windows/game.exe

      - name: Upload Web build
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web
          retention-days: 7

      - name: Call Discord Notifier
        uses: ./.github/actions/discord-notifier
        with:
          type: 'build'
          status: ${{ job.status }}
          branch: ${{ github.ref_name }}
          commit: ${{ github.sha }}
          actor: ${{ github.actor }}
          run_id: ${{ github.run_id }}
          discord_webhook: ${{ secrets.DISCORD_BUILD_TEST }}
          additional_info: "Web build completed and available as an artifact."