name: Create Release Tag (Alternative)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (format: X.Y) without "v" prefix'
        required: true
        type: string

permissions:
  contents: write

jobs:
  validate-version:
    runs-on: ubuntu-latest
    steps:
      - name: Validate version format
        id: validate
        run: |
          VERSION="${{ github.event.inputs.version }}"
          if ! [[ $VERSION =~ ^[0-9]+\.[0-9]+$ ]]; then
            echo "::error::Invalid version format. Must be in format X.Y (e.g., 1.0, 2.3)"
            exit 1
          fi
          echo "Version format is valid: $VERSION"
          echo "tag_name=v$VERSION" >> $GITHUB_OUTPUT
      
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Verify tag doesn't exist
        run: |
          TAG_NAME="v${{ github.event.inputs.version }}"
          if git ls-remote --tags origin | grep -q "refs/tags/$TAG_NAME$"; then
            echo "::error::Tag $TAG_NAME already exists"
            exit 1
          fi
          echo "Tag $TAG_NAME doesn't exist yet, we can proceed"
  
  create-release:
    needs: validate-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: Release v${{ github.event.inputs.version }}
          draft: true
          prerelease: false
          
      - name: Call Discord Notifier
        uses: ./.github/workflows/discord-notifier.yml@main
        with:
          type: 'release'
          status: 'success'
          branch: ${{ github.ref_name }}
          commit: ${{ github.sha }}
          actor: ${{ github.actor }}
          run_id: ${{ github.run_id }}
          additional_info: "v${{ github.event.inputs.version }}"
          discord_webhook: ${{ secrets.DISCORD_WEBHOOK }}