name: "Deploy to itch.io"

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENSE'

jobs:
  export_and_deploy:
    name: Export & Deploy
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: 0

      - name: Setup directories
        run: mkdir -p ~/.local/share/godot/export_templates ~/.config/godot/
          
      - name: Install dependencies
        run: apt-get update && apt-get install -y rsync wget unzip

      - name: Cache Godot export templates
        id: cache-templates
        uses: actions/cache@v3
        with:
          path: ~/.local/share/godot/export_templates
          key: ${{ runner.os }}-godot-templates-4.3

      - name: Download and install export templates
        if: steps.cache-templates.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_export_templates.tpz -O templates.tpz
          unzip -q templates.tpz
          mkdir -p ~/.local/share/godot/export_templates/4.3.stable
          mv templates/* ~/.local/share/godot/export_templates/4.3.stable/
          rm -rf templates templates.tpz

      - name: Web Build
        run: |
          mkdir -p build/web
          godot --headless --export-release "Web" ./build/web/index.html

      - name: Deploy to itch.io
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: web
          ITCH_GAME: ${{ secrets.ITCH_GAME }}
          ITCH_USER: ${{ secrets.ITCH_USER }}
          PACKAGE: build/web
          VERSION: ${{ github.sha }}
          BUILD_METADATA: github-${{ github.run_id }}