name: "Deploy to itch.io"

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENSE'

jobs:
  export_game:
    name: Export Game
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.2.1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: 0

      - name: Setup
        run: |
          mkdir -p ~/.local/share/godot/export_templates
          mkdir -p ~/.config/godot/
          ls -la
          
      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y rsync

      - name: Cache Godot export templates
        uses: actions/cache@v3
        with:
          path: ~/.local/share/godot/export_templates
          key: ${{ runner.os }}-godot-templates-4.2.1

      - name: Web Build
        run: |
          mkdir -p build/web
          godot --headless --export-release "Web" ./build/web/index.html || exit 1
          ls -la build/web

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web
          retention-days: 1

  deploy_to_itchio:
    name: Deploy to itch.io
    runs-on: ubuntu-latest
    needs: export_game
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: web-build
          path: build/web

      - name: Display structure of downloaded files
        run: ls -R build/web

      - name: Deploy to itch.io
        uses: manleydev/butler-publish-itchio-action@main
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: web
          ITCH_GAME: ${{ secrets.ITCH_GAME }}
          ITCH_USER: ${{ secrets.ITCH_USER }}
          PACKAGE: build/web
          VERSION: ${{ github.sha }}
          BUILD_METADATA: github-${{ github.run_id }}